### ISSUE TITLE
"social channels will be actively recommended during the onboarding sessions..."

### ISSUE THREAD

**Issue by RotaJimmy** [cjdnrota/Rota-marketing#13]
Can we think about this/ be careful. We do not want people who are rejected after assessments posting on our social media - An example of peoples possible (and worse case reactions) to being rejected came through today - 
![image](https://cloud.githubusercontent.com/assets/18699409/19697664/2bda35a8-9ae4-11e6-8999-9bea896fee96.png)

**Comment by jenschuring** [comment]
Hi Jimmy, 

yes, couldn't agree more that we have to be careful about this. The good thing about Facebook is that we have a profanity filter in place. In addition, we have put down a whole lot of words that when used will not allow the comment to be posted. Unfortunately we cannot rule out that there will still be occurrences, but at the same time we are dependent on an active social community. We are doing our best on monitoring the SM channels though, so hopefully instances like this email will not transfer.
