### ISSUE TITLE
Linkedin content drive

### ISSUE THREAD

**Issue by MarcBertorelli** [cjdnrota/Rota-marketing#15]
Hi all, 

I was wondering if we could start pushing some active content on Linkedin (its a great way to engage with potential partners). There are groups on their associated with hospitality part time staffing and other relevant topic areas. 

Let me know if you would also like some help from the sales team.

**Comment by jenschuring** [comment]
Hi Marc, 
you have full access to the ROTA profile now right? So we can start being more active here, definitely a good call! Thanks for the input :)
