### ISSUE TITLE
Heathrow Ads on nearby public transport?

### ISSUE THREAD

**Issue by WillTaylor22** [cjdnrota/Rota-marketing#16]
Inside / outside busses?
In the nearby tube stations?

Whatever method people use to get to the shifts...

**Comment by jenschuring** [comment]
Hi Will,
Thanks for this. I am in contact with Joe, who is in charge of the Nurture Programme at JCD, and have actually booked in a meeting with him regarding such possibilities on Monday. Outdoor advertising definitely has potential, but will come at a far greater cost than what we have done so far. We can give you an update about this if you'd like?

**Comment by cjdnrota** [comment]
Initial prices circa 20k.
