### ISSUE TITLE
Rota Newsletter

### ISSUE THREAD

**Issue by RotaJimmy** [cjdnrota/Rota-marketing#18]
Hi guys,

I love the newsletters, and the Member engagement you have both done of late, calendar etc.
However, please can we always try to have something relevant for all Geographies - dont want members in Birmingham & Manchester just seeing stuff about London all the time.
Ask myself & Ryan for some gossip/stories if you are struggling.

Cheers.
x

**Comment by jenschuring** [comment]
Hi Jimmy, 

thanks for that, I totally agree! We definitely need to have engaging content for everyone. Unfortunately I didn't have a story ready about up north for the last Newsletter, but I definitely want to include it into the next one, so if you can get me a inspiration, that would be much appreciated :) If you have one now, I can post about it on Social Media!
As for the Calendar, prizes will also be raffled out to Manchester and Birmingham people (you will actually have to take them up when you go back up next time).

Looking forward to our catch up later! 

Jen :)

**Comment by Ryancrout** [comment]
Hi Both

The main story up north is the Manchester Arena right now - loads of shifts available for them to work there for some really good events. Main one being the boxing on Saturday.

**Comment by jenschuring** [comment]
Brilliant, I will make that into a Facebook post and also potentially into a themed blog post! Thank you :)
