### ISSUE TITLE
Urgent Add-on for Members late to shifts

### ISSUE THREAD

**Issue by RotaSimone** [cjdnrota/Rota-marketing#7]
Could we have an add on in the admin panel where we can mark how many times a member has been running late to a shift/checked in late to a shift? So that we can keep an eye on members time keeping and ensure that we are giving out warnings when members are late too many times and for which venues they are running late for (it could be due to poor directions on the app). If this could be added either via the members profile, or even through the booking itself this would be a really great tool for ops to use to ensure our members are aware that lateness is not tolerated with rota.

Please let me know of any ideas you might have or if you need anymore information in regards to this enhancement please do not hesitate to ask.

Thanks

**Comment by jenschuring** [comment]
I'm not sure, but I think this would be more of a tech issue?

**Comment by RotaSimone** [comment]
thanks @jenschuring
